apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "vox-raga"
  namespace: "default"
  annotations:
    sidecar.istio.io/inject: "true"
    autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    autoscaling.knative.dev/target: "1"
    autoscaling.knative.dev/minScale: "1"
    autoscaling.knative.dev/maxScale: "2"
spec:
  predictor:
    containers:
      - name: kserve-container
        image: ghcr.io/bnallapeta/vox-raga:0.1 
        imagePullPolicy: Always
        env:
        - name: MODEL_NAME
          value: "tts_models/multilingual/multi-dataset/xtts_v2"
        - name: MODEL_DEVICE
          value: "cuda"
        - name: MODEL_COMPUTE_TYPE
          value: "float16"          
        - name: SERVER_LOG_LEVEL
          value: "info"
        - name: PYTHONPATH
          value: "/app:/root"
        - name: HOME
          value: "/root"
        - name: MAX_BATCH_SIZE
          value: "4"
        - name: MAX_BATCH_LATENCY
          value: "100"
        ports:
        - name: http1
          containerPort: 8888
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 8Gi
          requests:
            cpu: "500m"
            memory: 4Gi
        readinessProbe:
          httpGet:
            path: /health
            port: http1
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: http1
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
    imagePullSecrets:
    - name: acr-secret
