apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "tts-service"
  namespace: "default"
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  predictor:
    containers:
      - name: tts-service
        image: ${REGISTRY_IMAGE}
        env:
        - name: MODEL_NAME
          value: "tts_models/en/vctk/vits"
        - name: MODEL_DEVICE
          value: "cpu"
        - name: MODEL_COMPUTE_TYPE
          value: "float32"
        - name: SERVER_LOG_LEVEL
          value: "info"
        ports:
        - name: http1
          containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "500m"
            memory: 2Gi
        readinessProbe:
          httpGet:
            path: /ready
            port: http1
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: http1
          initialDelaySeconds: 120
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: model-cache
          mountPath: /tmp/tts_models
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
    volumes:
    - name: model-cache
      emptyDir: {}
    imagePullSecrets:
    - name: ${REGISTRY_SECRET_NAME} 