apiVersion: apps/v1
kind: Deployment
metadata:
  name: vox-raga-gpu
  labels:
    app: vox-raga
    component: tts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vox-raga
      component: tts
  template:
    metadata:
      labels:
        app: vox-raga
        component: tts
    spec:
      containers:
      - name: vox-raga
        image: bnracr.azurecr.io/vox-raga:0.0.18
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 8888
        env:
        - name: MODEL_NAME
          value: "tts_models/multilingual/multi-dataset/xtts_v2"
        - name: MODEL_DEVICE
          value: "cuda"
        - name: SERVER_LOG_LEVEL
          value: "info"
        - name: PYTHONPATH
          value: "/app:/root"
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: vox-raga
  labels:
    app: vox-raga
    component: tts
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
  selector:
    app: vox-raga
    component: tts 
